### ISSUE TITLE
Make a basic native output example (using LLVM?)

### ISSUE THREAD

**Issue by trusktr** [bytescript/bytescript#22]
Similar to https://github.com/bytescript/bytescript/issues/11, but output the basic example to native.

Let's start with this:

```ts
function sum(a: i32, b: i32): i32 {
  return a + b
}

export { sum }
```

then somehow import that or embed into a native C or Rust program and call it.

**Comment by trusktr** [comment]
@ZoeDreams

**Comment by p3nGu1nZz** [comment]
working on #11 first. then this.

**Comment by p3nGu1nZz** [comment]
After researching and considering our project goals, it appears that using LLVM with Emscripten may not be the most optimal solution for our directive. While it does work, it presents several challenges and does not provide a concise or reduced solution. Upon further research, we have determined that implementing WASI would be a better approach. This would standardize our WASM modules with a bootstrap, allowing our ByteScript programs and modules to be interoperable.

Reasons for choosing WASI over LLVM with Emscripten:
- WASI provides a standardized interface for WASM modules, making them more portable and interoperable.
- WASI allows us to avoid the complexity and overhead of using Emscripten with LLVM.
- WASI is specifically designed for use with WASM, making it a more natural fit for our project.

Possible caveats of our implementation:
- WASI is still a relatively new technology and may have limitations or issues that are not yet fully understood.
- Our implementation may require additional development time and resources to ensure compatibility with WASI.
- There may be challenges in integrating WASI with other parts of our system or with third-party tools and libraries.

Please see issue #28 for an updated abstract of our epic task.

Joke Time:
Why did the developer add WASI-ABI to their sushi? 
To give it a little extra byte!
